server:
  port: 10002
spring:
  application:
    name: springboot-job
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8&useSSL=false
    username: root
    password: chendongsuo
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
